### ISSUE TITLE
File "fast_video.py", line 84, in <module>

### ISSUE THREAD

**Issue by rergw** [gusals3587/jumpcutterV2#2]
I got this problem when trying your script.

[gist](https://gist.github.com/rergw/ed8dcff4575c8bc1dac1bfa19d3c5a53).

Is this the relevant part?:

```
Traceback (most recent call last):
  File "fast_video.py", line 84, in <module>
    if getMaxVolume(audioChunk) < 500:
  File "fast_video.py", line 34, in getMaxVolume
    maxv = np.max(s)
  File "<__array_function__ internals>", line 6, in amax
  File "/home/distinct/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2668, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/home/distinct/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

```

**Comment by gusals3587** [comment]
Can I see the video file you tried?

BTW the video is outputted to spedup.mp4 and the audio is at spedupAudio.wav so you could use ffmpeg to put the audio and video together. (In fact, that's exactly what the program does)
